### ISSUE TITLE
[Channel Permissions] Add configurable mouse hover delay before showing

### ISSUE THREAD

**Issue by Saud-97** [Farcrada/DiscordPlugins#89] opened 2022-05-28 11:54 UTC
### Is your request related to a problem? Please describe.

I don't like having to always view channel permissions when I'm changing channels and hovering for like half a second.

### Describe the solution you'd like

Have the ability to set a delay for mouse hover then it triggers showing the pop up. For example a user want's 500ms hover delay. For me I would prefer 1500ms delay.

### Additional context

I have saw that `popoutDelay: 250` exists in the config section. But there was no delay for the hovering. Which I think should be more relevant than the implemented delay.

Also why don't you utilize the plugin settings section for easy user configurations changing.
![image](https://user-images.githubusercontent.com/39028181/170824450-edfe658a-0377-41f6-ba72-369c28d1e528.png)

**Comment by Farcrada** [comment] 2022-05-30 17:43
Noted and duplicate of #54 

I have an update in the works that will have a look at this.

**Closed by Farcrada** 2022-05-30 17:43 UTC
Labels: enhancement

**Comment by Saud-97** [comment] 2022-05-30 21:29
btw this should be closed as completed instead of not planned but oh well it's just a minor status.

**Comment by Farcrada** [comment] 2022-05-31 07:14
If you hover over `not planned` it gives the possibility of `duplicate`, I suppose it looks a bit weird though.

**Comment by Saud-97** [comment] 2022-05-31 19:31
> If you hover over `not planned` it gives the possibility of `duplicate`, I suppose it looks a bit weird though.

yeah it definitely gives the wrong impression.
