### ISSUE TITLE
[HideChannels] Hide Channels button duplicates when alt tab to discord

### ISSUE THREAD

**Issue by UltimateBoi** [Farcrada/DiscordPlugins#59] opened 2021-09-08 12:12 UTC
### Describe the bug

Basically when i alt tab back to discord it duplicates the hide channels / dms button in this plugin.

### Expected behavior

Not meant to duplicate when i alt tab to discord

### To reproduce

1. alt tab to and from discord a shit ton of times
2. it will duplicate.
3. ez dupe

### Screenshots

![image](https://user-images.githubusercontent.com/63293118/132506899-469cbaad-ab7b-4c9d-acb3-d322f302ee3a.png)

### Discord version

Stable

### OS version

Windows 10

### Additional context

nothing except this is very funny lol

**Comment by Farcrada** [comment] 2021-09-08 13:31
What a weird occurrence. I'll have a look.

**Comment by Farcrada** [comment] 2021-09-08 13:34
Ah! There might be an issue with the previous version.
What plugin version do you have currently?

I'll add that to the submission form as well. Might help as well.

**Comment by Farcrada** [comment] 2021-09-22 19:31
Closing since no reply has been received and I presume this to be fixed.

**Comment by OlavWolfiken** [comment] 2021-09-28 22:06
![image](https://user-images.githubusercontent.com/50549647/135172182-64baceb6-f46a-4345-8c41-017193348587.png)
Nah, sadly it's not

**Comment by OlavWolfiken** [comment] 2021-09-28 22:11
> ![image](https://user-images.githubusercontent.com/50549647/135172182-64baceb6-f46a-4345-8c41-017193348587.png) Nah, sadly it's not
> 
> Edit: I'm on version 2.0.5

It's actually doing that randomly for me now, can't force it to duplicate. Sometimes it will add one more, other time it will do the opposite, for now I can't find any pattern of behaviour

**Comment by OlavWolfiken** [comment] 2021-09-28 22:12
@Farcrada

**Comment by Farcrada** [comment] 2021-09-29 17:35
I couldn't reproduce either. If you only got `Hidden Channels` enabled, well.. assuming you know the frequency of it, does it happen on it's own? Without any other plugins?

I also see that the # is gone from the screenshot, unlike in the first one. Does that only happen sometimes or is that expected?

**Comment by UltimateBoi** [comment] 2021-10-17 19:55
it just duplicates when i alt tab back an forth through discord and chrome (rlly any app just using an example...)

**Closed** 2021-11-14 15:03 UTC
Labels: bug, more information
