### ISSUE TITLE
(BUG) Settings doesn't open and can't see Channel Permission

### ISSUE THREAD

**Issue by Randomdudeforsomereason** [Farcrada/DiscordPlugins#119] opened 2022-11-08 09:55 UTC
### Describe the bug

Don't know why settings doesn't open

I can't see the Permission of the Channels

### Expected behavior

Setting supposed to open

I should able to see Channel Permission

### To reproduce

For Settings that couldn't open
1. Go to User Settings
2. Go to Plugins
3. Find Channel Permission
4. Click the Gear Icon
For Channel Permission not appearing
1. Hover your mouse over any Channel

(Don't know if this bugs appears to every person)

### Screenshots

https://gyazo.com/01ee625f0f0c3c6ed9a15eba64f2e05e For the Setting

https://gyazo.com/5cc3f96b9b47f34ce27fb0f2813d04d3 For the Channel Permission not appearing

### OS version

10

### Discord version

Stable

### BetterDiscord version

v1.8.2

### Plugin version

v4.2.4

**Comment by Farcrada** [comment] 2022-11-08 16:04
Duplicate of https://github.com/Farcrada/DiscordPlugins/issues/112

**Closed by Farcrada** 2022-11-08 16:04 UTC
Labels: bug
