### ISSUE TITLE
[Channel Permissions] Sometime that window go to upper left

### ISSUE THREAD

**Issue by Krystianh42** [Farcrada/DiscordPlugins#60] opened 2021-09-11 20:33 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/27408012/132960798-bd4a3951-1f4b-457f-8b0c-c1ff9d5ea350.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/27408012/132960798-bd4a3951-1f4b-457f-8b0c-c1ff9d5ea350.png)
I mean that window it should be in place and not fly around the corners.

### OS version

Windows 10 latest version

### Discord version

Stable latest

### BetterDiscord version

1.2.1

### Plugin version

v3.7.4

**Comment by Farcrada** [comment] 2021-09-13 13:54
Duplicate of https://github.com/Farcrada/DiscordPlugins/issues/28

Keep in mind, update is soon to come that resolves this. Have a look at this:

**Closed by Farcrada** 2021-09-13 13:54 UTC
Labels: bug
